### ISSUE TITLE
peer dependency on react 0.12.1

### ISSUE THREAD

**Issue by fabriziomoscon** [NdYAG/react-rater#1]
Hi @NdYAG,

We are using your library for start rating and works great!
But I was wondering if there is any reason to enforce the peerDependency on `react` `0.12.1`
https://github.com/NdYAG/react-rater/blob/master/package.json#L32

If not, could you remove it? Because using npm older than v 3 it prevent us to update to react > 0.12.1 as npm throws errors:

```
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "npm" "install" "react-rater" "--save"
npm ERR! node v0.10.31
npm ERR! npm  v2.6.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-rater@0.1.0 wants react@^0.12.1

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fab/projects/Web-Provider/npm-debug.log
```

**Comment by NdYAG** [comment]
@fabriziomoscon 
Removed. 
Thanks for feedback : D

**Comment by fabriziomoscon** [comment]
Thank you!

**Comment by fabriziomoscon** [comment]
Hi @NdYAG 

Apologies for reopening the issue, but I found out today a problem with this fix.
Basically I use `webpack` to build a `bundle.js` with all the `npm` modules required in my app which breaks when I run it.
`Uncaught ReferenceError: React is not defined`

So removing `peerDependencies` caused `React` not to be found in the final built.

There are 2 solutions I can see now:
- re-add peerDependencies with `"react": ">=0.12.1"`
- add react as a dependency like https://github.com/quickleft/react-loader/blob/master/package.json#L37

I found out others with this problem:
https://github.com/rackt/react-router/issues/98
https://github.com/syranide/react-swf/issues/4
https://github.com/yahoo/react-intl/issues/79

**Comment by NdYAG** [comment]
@fabriziomoscon 
`package.son` updated: https://github.com/NdYAG/react-rater/commit/be5dc35998a8f4e1eeb93daa09f999e9a38c9bdd

**Comment by NdYAG** [comment]
Sorry for bring this up again.
I've upgrade this lib to version 0.2.1, for webpack users
`import Rater from react-rater` won't throw error `React is not defined` like in 0.1.0
