### ISSUE TITLE
React Rater doesn't update on React Starter Kit (React V15.4.1)

### ISSUE THREAD

**Issue by gmaijoe** [NdYAG/react-rater#10]
The visual stars just stay blue and don't change to yellow. Super confused.

When I hover, the source code does say it's active or not (or will be active) but there is no change in the visual looks.

[http://imgur.com/a/OyeWB](url)

**Comment by NdYAG** [comment]
Have you assigned different colors to `$react-rater-link`, `$react-rater-hover` & `$react-rater-active` in your own styling files?

**Comment by NdYAG** [comment]
Hey @gmaijoe  I've update react-rater to a new version.
Even though I don't know the exact reason of your question, I think you could try to upgrade and see if it works.
