### ISSUE TITLE
onRate function never returns the original event

### ISSUE THREAD

**Issue by pantchox** [NdYAG/react-rater#12]
Hi,

I have created a onRate function which is getting called if i hover/click etc
but i want it to be called only when it is clicked, in the readme it is mentioned when it is NOT click it will return an object with property of `originalEvent: Event` which i never get on either event.

Thanks.

**Comment by NdYAG** [comment]
Hi @pantchox 
Thanks for reporting the bug! You could now update to 0.4.2 and handle the callback argument like this:
https://github.com/NdYAG/react-rater/blob/master/example/index.js#L36

`rating` is now passed with the SyntheticEvent's other attributes.

**Comment by pantchox** [comment]
thanks it works now :)
