### ISSUE TITLE
Class names not added to star objects on touch devices.

### ISSUE THREAD

**Issue by shanmukh15** [NdYAG/react-rater#14]
Hi , I had installed the latest react-rater component from npm. I see the stars respond to event handler properly but visual feedback is missing. On debug, i found the CSS style classes are not appended properly on touch events. Could you help with a fix.

i am using the Rater component with just total and handler function. On my ipad/iphone and Android , i see the stars are always grey(#CCC).

**Comment by NdYAG** [comment]
Hi @shanmukh15
Thank you for reporting it. Could you tell me the react version you are using? Thank you.

**Comment by NdYAG** [comment]
Hi @shanmukh15 
I've tested it on my mobile device, the star works normally.
Please make sure that `interactive` attribute is not false, and try again.
Feel free to reopen this issue any time.
