### ISSUE TITLE
Export sass file

### ISSUE THREAD

**Issue by etienne-lambert** [NdYAG/react-rater#17]
Hi,

The scss file should be included in the lib, so that "the CSS way" of styling from the doc works.
I'm not familiar enough with webpack to make the required change, though that should be easy for someone with experience.
Note that css and scss files should have different names (maybe react-rater-sass.scss) for easier import.

**Comment by NdYAG** [comment]
Hi @etienne-lambert ,
The sass file is compiled to css file in `lib`. Right now to import the css file, you need import it like this,
```js
import 'react-rater/lib/react-rater.css'
```

**Comment by etienne-lambert** [comment]
Hi. I know but if you want to change the star colors as mentionned in your doc you need the scss file not the css file. I suggest you should export both.

**Comment by NdYAG** [comment]
Hi @etienne-lambert,
thank you for the advice. Now sass file is included into `/lib`.
https://github.com/NdYAG/react-rater/commit/9284b8887445a4ff9c21f517aba8a6a52aacc6a4
Please update to 0.4.8.
