### ISSUE TITLE
React-rater can't work normally with `Too many request` (HTTP status code 429).

### ISSUE THREAD

**Issue by AChaoZJU** [NdYAG/react-rater#20]
In the following code,  http request is sent in `onRate`.
Props `rating` is rendered with redux's mapStateToProps.

```
gradeQuestion = (question, e) => {
    if (e.rating && e.rating !== question.grade) {
      this.props.gradeQuestion(question.id, e.rating)  // This is an action which sends http request
    }
  }
```
```
 <Rater total={5} rating={question.grade} onRate={e => this.gradeQuestion(question, e)} />
```
It works well except the `Too many request` (HTTP status code 429).

![screenshot from 2018-05-19 19-51-30](https://user-images.githubusercontent.com/17509647/40268340-2bc720a4-5b9e-11e8-8a77-5d8ef4bd56bc.png)

![image](https://user-images.githubusercontent.com/17509647/40268357-5a781944-5b9e-11e8-8c45-0f7ae78ace67.png)

**Comment by NdYAG** [comment]
Hi @AChaoZJU ,

To make interface for developers are straightforward and simple,
now `onRate` will be called before rating, during rating and after rating. 
https://github.com/NdYAG/react-rater#callback

To make sure that `onRate` will be called only one time, you could now use this workaround.

```
    if (e.type === 'click' && e.rating && e.rating !== question.grade) {
```

Yet this is a known problem. To call `onRate` callback even during rating (mouse moving between star)  is not ideal. I'll implement a new version to distinguish these three events later.

**Comment by AChaoZJU** [comment]
@NdYAG  thank you for answer. It works well. Look forward to your new version.
