### ISSUE TITLE
Warnings on a DOM Element

### ISSUE THREAD

**Issue by coldfish** [NdYAG/react-rater#21]
I'm getting warnings for DOM elements. I couldn't understand what triggers the problem although I debugged the source code.

`Warning: React does not recognize the `isActive` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isactive` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Star)
    in Star (created by Rater)
    in div (created by Rater)
    in div (created by Rater)
    in Rater (at RecipeCard.js:128)
    in div (created by styled.div)
    in styled.div (at RecipeCard.js:127)
    in div (created by styled.div)
    in styled.div (at RecipeCard.js:123)
    in div (created by styled.div)
    in styled.div (at RecipeCard.js:103)
    in RecipeCard (created by Connect(RecipeCard))
    in Connect(RecipeCard) (at Recipes.js:89)
    in div (created by styled.div)
    in styled.div (at Recipes.js:87)
    in section (created by styled.section)
    in styled.section (at Recipes.js:85)
    in div (at Recipes.js:80)
    in Recipes (created by Connect(Recipes))
    in Connect(Recipes) (at RouteContainer.js:11)
    in div (at Base.js:21)
    in div (created by styled.div)
    in styled.div (at Base.js:13)
    in Base (at RouteContainer.js:10)
    in Route (at RouteContainer.js:7)
    in DefaultRoute (at MainRouter.js:12)
    in Switch (created by MainRouter)
    in Router (created by BrowserRouter)
    in BrowserRouter (at MainRouter.js:10)
    in MainRouter (created by Root)
    in Provider (at Root.dev.js:7)
    in Root (at index.js:9)`

Getting extra three others warnings for these props : 'willBeActive', 'isActiveHalf', and 'isDisabled'.

It will be great if I can get any answers.. Thanks for the library.

**Comment by NdYAG** [comment]
@coldfish 
Thanks for reporting the bug. I've seen this before with React 0.14 but not with current version, could you tell what version of React are you using?
But still it's better to remove those unwanted props, I'll comment here once it's implemented. For now you can ignore those warnings.

**Comment by coldfish** [comment]
@NdYAG react version is 16.4.1. Only thing I can see, I wrapped the rater with a styled-component div. Thanks for the comments.

**Comment by NdYAG** [comment]
@coldfish Thanks!  A new version `5.0.2` is published to npm, please check out if the warning are eliminated.
Again thanks for reporting 🍻

**Comment by coldfish** [comment]
Thanks @NdYAG for the new version, you're fast !

**Comment by NdYAG** [comment]
@coldfish 
😎My pleasure.
I'll close the issue. Re-open if there're any other problems about it.
