### ISSUE TITLE
Warning: Unknown event handler property `onRating`. It will be ignored.

### ISSUE THREAD

**Issue by omidnikrah** [NdYAG/react-rater#22]
Hi,
When Rater component mount, logged following error:
```
Warning: Unknown event handler property `onRating`. It will be ignored.
```
But component working good.
Why?

**Comment by NdYAG** [comment]
Hi @omidnikrah ,
Thanks for pointing this out! I've checked the code and found that it's introduced in latest version.

The newly added `onRating` & `onCancelRate` would be set on DOM node, which is not suggested by React. That's the reason why it threw a warning.

Now it will not do anything bad to your code, but I will fix it soon.

Thank you!

**Comment by NdYAG** [comment]
@omidnikrah 
I'll tell you once a new version is published.

**Comment by NdYAG** [comment]
@omidnikrah 
A new version `5.0.3` is published to npm. And here's the code changes,
https://github.com/NdYAG/react-rater/commit/e91cc96cb42f32f4f31cf952ac16b1fc30a64ce8

Again thanks for reporting this issue. :D
