### ISSUE TITLE
onMouseEnter issue

### ISSUE THREAD

**Issue by anissaHireme** [NdYAG/react-rater#23]
Hi react rater team, in some cases onMouseEnter is not enough to define the selected "star", onMouseOver could be a solution to that.. is there a way for me to use onMouseOver instead of onMouseEnter to call onRating ?

**Comment by NdYAG** [comment]
Hi @anissaHireme 
In most cases `onMouseEnter` & `onMouseOver` work the same, but you could send a pull request for that (or I could add support for that later). I'm wondering in what kind of case `onMouseEnter` doesn't work?

**Comment by NdYAG** [comment]
Hi @anissaHireme , last month I've been really busy, sorry for replying late. A version 5.04 is now available on npm and solves this issue. Checkout and any following issues are welcomed. I'll close this issue then, reopen if necessary.

**Comment by NdYAG** [comment]
For changes see https://github.com/NdYAG/react-rater/commit/8425b2708e32b47bb3a8efe00fa587a290443a54
