### ISSUE TITLE
fractional value

### ISSUE THREAD

**Issue by xBootstrap** [NdYAG/react-rater#27]
Hi,

Thank you for the great resource, is that possible to add fractional value for example rating={4.6}

**Comment by NdYAG** [comment]
hi @xBootstrap 
sorry for late response 
rater support fractional value when `interactive` attribute is set as `false`.
A half star will be rendered.

**Comment by NdYAG** [comment]
Please checkout https://github.com/NdYAG/react-rater#read-only-mode for more.
If there're any other questions about it, please re-open this issue.
Thanks for reporting.
