### ISSUE TITLE
Possibility to disable the component

### ISSUE THREAD

**Issue by eques** [NdYAG/react-rater#3]
Sometimes, i want to render this component in read-only mode.

**Comment by NdYAG** [comment]
Hi, @eques 
Thanks for your advice.

I'll consider add an `interactive` prop in the next version.

Right now, you could create a read-only rater by importing the star component:

```js
import { Star } from 'react-rater'

render() {
//...<Star />
}
```

and you may have to disable the style for this read-only rater.

Sorry for the inconvenience. I'll also consider remove the style requirement in next version.

**Comment by NdYAG** [comment]
Hi @eques
you could try out version 0.3.0,
I've added an `interactive` attribute for read-only raters.
Here's an example: https://rawgit.com/ndyag/react-rater/master/example/index.html

**Comment by NdYAG** [comment]
I'm closing this issue since the new version works fine for me.
Reopen it anytime if you have any other questions.

**Comment by eques** [comment]
Thank you so much for the speedy reply :) It works :+1:
