### ISSUE TITLE
Can we do decimals??

### ISSUE THREAD

**Issue by gorkamolero** [NdYAG/react-rater#52]
Thank you!

**Comment by NdYAG** [comment]
@gorkamolero By default in readonly mode you can have code like this `<Rater rating={2.5} interactive={false} />` 
If need more precise control the component supports customized star, for example, you can have some code like 
```
<Rater total={10}>
  <LeftStar/>
  <RightStar/>
</Rater>
```
which renders visually 5 stars.

**Comment by NdYAG** [comment]
Feel free to reopen the issue if this doesn't answer your question.
