### ISSUE TITLE
Set min value

### ISSUE THREAD

**Issue by costaoeste** [NdYAG/react-rater#8]
Its possible to block the stars on a min value? Example... 1 to 5 stars block 1 to 3, only 4 and 5 are available.
Thanks

**Comment by NdYAG** [comment]
Hey @costaoeste 

Sorry for response late.

Currently react-rater do not support min value, but I'll try to add one more attribute for it, or figure a workaround for you when I have time.

**Comment by NdYAG** [comment]
Hi @costaoeste 
Sorry again for not responding earlier.
Right now I've update rater to version 0.4. And `limit` is removed as we can append or prepend stars to get the same result.
Take a look at `example/LimitedRater.js`, there you could set `min` & `max` both for it.
I'm closing this issue, and feel free to reopen it.
